version: '3.8'

services:
  mailtocall-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailtocall-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mailtocall-network

networks:
  mailtocall-network:
    external: true
